### ISSUE TITLE
Typo in your plugin description at Wordpress.org

### ISSUE THREAD

**Issue by porg** [joppuyo/disable-media-pages#34]
Typo in your description at https://wordpress.org/plugins/disable-media-pages/
> SEARCH ENGINE OPTIMIZATION
> Even worse, attachment pages may in some cases rank higher **that** your actual content pages which leads to a poor user experience.

Should be "than" instead of "that" I assume.

Thanks a lot for providing this plugin!
- The Wordpress core feature "Media Pages" creates an abundance of duplicate-content and wastes valuable slug-namespace.
- That annoyed me, and your plugin just fixes that.
- Also mangled existing media pages without any issues with it. 
- Thanks!

**Comment by joppuyo** [comment]
Hey!

Glad you like the plugin and thanks for bringing this issue to my attention!

This has been fixed in the latest version of the plugin.
