### ISSUE TITLE
Restore media slugs

### ISSUE THREAD

**Issue by joppuyo** [joppuyo/disable-media-pages#4]
Add wizard to restore random UUID media slugs back to readable slugs based on the attachment name.

**Comment by porg** [comment]
Hi, I'm currently building my portfolio website with Wordpress.
- According to your FAQ, fresh websites with no media slugs yet in the search engine indexes are good candidates for starting correctly right from the beginning.
- Nevertheless strategically thinking, not having an exit strategy for plugin usage is never a good idea.
- So I would very much appreciate a "restore" feature. Is there already a timeline for this?

**Comment by joppuyo** [comment]
Unfortunately I currently have some health issues, but I will be able to work on this plugin in a month or two.

This feature should be quick to implement as soon as I have time to work on the plugin.

**Comment by porg** [comment]
Thanks for the info! An be well, all the best for your health!

**Comment by joppuyo** [comment]
A quick update, I currently have this functionality working, I just need to do some modifications to the admin page so the end-user can run the conversion process. When this is done, I'll release an updated version of the plugin with the restore functionality.

**Comment by joppuyo** [comment]
Hey, I just released version 1.1.0 with this functionality. I'm closing this ticket, but if you have any problems just write a comment and I'll reopen the issue.
